language: go

go:
    - tip
    - 1.3
    - 1.2

services:
    - redis-server

env:
    - TEST_REDIS_ADDRESSES=localhost:6379 TEST_REDIS_WAIT_DURATION=10s

before_script:
    - sh -c "sleep 5"  # give Redis a(n additional) chance to start

script:
    - go test -v ./...

